@extends('layouts.app' ,['disableHeader' => true])

@push('title')
    {{ __('Verify') }}
@endpush

@section('content')
    <div class="signLog-section">
        <div class="right" data-background="{{ getFileUrl(getOption('login_right_image')) }}">
            <a href="{{ route('frontend') }}" class="logo"><img src="{{ getFileUrl(getOption('app_logo')) }}"
                                                                alt=""/></a>
            <h4 class="title">
                {{ getOption('auth_page_title') }}
            </h4>
        </div>
        <div class="left">
            <div class="wrap">
                <div class="zMain-signLog-content">
                    <div class="pb-30">
                        <h4 class="fs-sm-36 fs-26 fw-600 lh-sm-46 lh-20 text-title-text pb-5">{{ __('2FA Authentication') }}</h4>
                        <p class="fs-18 fw-500 lh-28 text-para-text"> {{ __('Hello') }} {{ auth()->user()->name }},
                            <br/>
                            {{ __('Enter the verification code generated by your mobile application (Google Authenticator)')
                            }}</p>
                    </div>
                    <form action="{{ route('google2fa.authenticate.verify.action') }}" method="post">
                        @csrf
                        <div class="row rg-20 pb-15">
                            <div class="col-md-12">
                                <div>
                                    <label for="one_time_password" class="zForm-label">{{ __('Enter your authentication
                                    code') }}</label>
                                    <input type="text" name="one_time_password" required
                                           value="{{old('one_time_password')}}"
                                           class="form-control zForm-control"
                                           id="one_time_password"
                                           placeholder="{{ __('Code') }}"/>
                                    @error('email')
                                    <span class="fs-12 text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="flipBtn sf-flipBtn-primary w-100">{{ __('Continue') }}</button>
                    </form>
                    <h4 class="fs-14 fw-400 lh-24 pt-25">{{ __('If you lost your phone or uninstall the google authenticator
                    app and enable to access your account please contact with us.') }}</h4>
                </div>
            </div>
        </div>
    </div>
@endsection
